# Generated by Django 4.2.1 on 2023-05-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='sending_status',
            new_name='status',
        ),
    ]
